# Generated by Django 5.2.7 on 2025-11-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='posts/attachments/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
    ]
