# Generated by Django 5.2.7 on 2025-11-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_badge_alter_profile_user_announcement_profile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='can_access_admin_panel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='can_moderate_global_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='can_send_announcement',
            field=models.BooleanField(default=False),
        ),
    ]
