# Generated by Django 5.2.7 on 2025-11-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_badge_can_access_admin_panel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_university',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
