# Generated by Django 5.2.7 on 2025-11-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_announcement_target_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
