# Generated by Django 5.2.7 on 2025-11-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_badge_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='can_access_admin_panel',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='can_moderate_global_posts',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='can_send_announcement',
        ),
        migrations.AlterField(
            model_name='badge',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
