# Generated by Django 5.2.7 on 2025-11-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_announcement_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
