"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import dj_database_url
import base64
import json
import os
from google.oauth2 import service_account
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-sua-chave-local')

# O Render define 'DEBUG' como 'False' em produção automaticamente se você setou a env var
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '192.168.15.164:5173']

# Adiciona o domínio do Render automaticamente
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'storages',          # Para o Google Cloud Storage
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    
    # 'channels',        # Comentado para o MVP (WSGI Only)

    # Local apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Essencial para arquivos estáticos no Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',      # Deve vir antes do CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Configuração WSGI (Padrão para o Render neste MVP)
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Se NÃO existir (Ambiente Local), usa SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# ARQUIVOS ESTÁTICOS (CSS, JS, Images do Admin) - Whitenoise
# ==============================================================================
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ==============================================================================
# ARQUIVOS DE MÍDIA (Uploads) - Google Cloud Storage / Firebase
# ==============================================================================

FIREBASE_STORAGE_BUCKET = os.environ.get('FIREBASE_STORAGE_BUCKET')
FIREBASE_SERVICE_ACCOUNT_KEY_B64 = os.environ.get('FIREBASE_SERVICE_ACCOUNT_KEY_B64')

# Configuração do django-storages
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = FIREBASE_STORAGE_BUCKET
GS_FILE_OVERWRITE = False  # Não sobrescreve arquivos com mesmo nome

# URL pública para acessar os arquivos
MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'

# Processamento da Chave de Serviço (Base64 -> JSON -> Credentials Object)
if FIREBASE_SERVICE_ACCOUNT_KEY_B64:
    try:
        decoded_json = base64.b64decode(FIREBASE_SERVICE_ACCOUNT_KEY_B64).decode('utf-8')
        service_account_info = json.loads(decoded_json)
        GS_CREDENTIALS = service_account.Credentials.from_service_account_info(service_account_info)
    except Exception as e:
        print(f"ERRO CRÍTICO: Falha ao carregar credenciais do Firebase: {e}")
        GS_CREDENTIALS = None
else:
    GS_CREDENTIALS = None # Fallback local ou erro se estiver em produção


# ==============================================================================
# DRF & CORS
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ]
}

# Adicione aqui a URL do seu Front-end na Vercel quando tiver
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://192.168.15.164:5173',
    # 'https://seu-app-universe.vercel.app',  <-- Adicione isso depois
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# CHANNELS (Desativado para MVP WSGI no Render Free)
# ==============================================================================
# Se ativar isso sem um Redis rodando, o deploy vai falhar ou dar erro 500.

# ASGI_APPLICATION = 'config.asgi.application'
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }